# Change 'comments' to true for Disqus comments
disqus:
  comments: false
  disqus_shortname: 'was-albi'

# If you are not using Google Analytics, please change 'google-ID' to an empty string
google-ID: ''


#-------------------------------
# Author Settings
author:
  name: Albi
  image: self_potrait.jpg
  bio: some info about this place and its name

#--------------------------------

menu:
#- {name: 'CV', folder: 'pages', file: 'CV.pdf'}
#- {name: 'Projects', folder: 'pages', file: 'projects.html'}
- {name: 'Notebook', folder: 'pages', file: 'notebook-homepage.html'}
- {name: 'Ramen', folder: 'pages', file: 'ramen-homepage.html'}
- {name: 'Lists', folder: 'pages', file: 'list-of-lists.html'}


# Available social icons are powered by Font Awesome, so you can use any icon that they offer
social:
- {icon: 'twitter', link: 'https://twitter.com/was_albi'}
- {icon: 'github', link: 'https://github.com/was-albi'}
#- {icon: 'spotify', link: 'https://open.spotify.com/user/thecapitalq?si=0d59e57aa96d4df7'}
- {icon: 'envelope', link: 'mailto:alberto.colombo@polimi.it'}


# Customize site text
# pagination:
  # next_page: ''
  # previous_page: ''

# sharing_button_prompt: ''

# related_posts: 'You may also enjoy...'

post_date_prefix: 'Written on'
